services:
  - type: web
    name: background-remover-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:10000
    plan: free
    region: oregon
    branch: main
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
