services:
  - type: web
    name: background-remover-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    region: oregon
    branch: main
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
